[package]
name = "treeshake-events"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
regex = { version = "1.10.5", features = ["std", "perf"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.120"
swc_core = { version = "0.96.*", features = ["ecma_plugin_transform"] }

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
